Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.

You may assume that each input would have exactly one solution, and you may not use the same element twice.

You can return the answer in any order.

 

Example 1:

Input: nums = [2,7,11,15], target = 9
Output: [0,1]
Output: Because nums[0] + nums[1] == 9, we return [0, 1].
Example 2:

Input: nums = [3,2,4], target = 6
Output: [1,2]
Example 3:

Input: nums = [3,3], target = 6
Output: [0,1]
 

Constraints:

2 <= nums.length <= 103
-109 <= nums[i] <= 109
-109 <= target <= 109
Only one valid answer exists.

In [6]:
import pandas as pd
import numpy as np

Here is my solution I derived from the work shown later on.

In [1]:
l1 = [2,7,11,15]
t1 = 9

import pandas as pd
import numpy as np

def twoSum(array, target):
        
    '''Inputs are an array of integer numbers and an integer  target. Outputs the indices of two
    numbers such that they add up to the target

    NOTE: For input array with exactly one solution and element only used once.
    '''
    indices_array = []
    n = len(array) #Length of array

    if n > 2:
        # Multiple index possible solution
        for i, num in enumerate(array):
            print(i)
            l1 = array.copy()
            l1[i] = target+5 #make interger outside of target at selected index 
            print(l1)
            result = np.where(np.array(l1)+num == target)[0]
            print(result)
            if result.size > 0:
                indices_array.append(i)
                indices_array.append(int(result))
                return indices_array

            else:
                continue
    elif n == 2:
        # One possible solution
        return [0,1] 

    else:
        return None  


Below are the arrays used to test the function

In [3]:
twoSum(l1, t1)

0
[14, 7, 11, 15]
[1]


[0, 1]

In [4]:
twoSum([3,2,4], 6)

0
[11, 2, 4]
[]
1
[3, 11, 4]
[2]


[1, 2]

In [5]:
twoSum([3,3], 6)

[0, 1]

In [6]:
twoSum([0, 4, 3, 0], 0)

0
[5, 4, 3, 0]
[3]


[0, 3]

In [7]:
twoSum([-1, -2, -3, -4, -5], -8)

0
[-3, -2, -3, -4, -5]
[]
1
[-1, -3, -3, -4, -5]
[]
2
[-1, -2, -3, -4, -5]
[4]


[2, 4]

Below is how I tested my program to get it to work

In [98]:
l1 = [2,7,11,15] #Here is a test array
t1 = 9 #Here is a test target
l2 = l1.copy() #we copy the test array 
indice = 0 # set indice to 0

# Here we thought about doing a destructive method
num1 = l2.pop(indice) #removes first integer from array
l1, l2, num1

([2, 7, 11, 15], [7, 11, 15], 2)

In [99]:
#With a numpy array we can add a value to each value in the array
np.array(l1) + num1

array([ 4,  9, 13, 17])

In [100]:
result = (np.array(l1) + num1) == t1 # This checks each array value to see which is equal to the target
result

array([False,  True, False, False])

In [101]:
result.any() #checks to see if there are any true values in the result array
#decided not to go with this method b/c we don't know where it is true

True

In [102]:
# Here we find out where it is true
np.where(((np.array(l1) + num1) == t1) ==True)[0]

array([1], dtype=int64)

In [103]:
indice_array = [] #initiate empty array  for placing each index where true occurs

In [104]:
indice_array.append(indice) #We store the first index that results in a true value in results
indice_array.append(int(np.where(((np.array(l1) + num1) == t1) ==True)[0])) #second index value stored
indice_array

[0, 1]

In [29]:
# Looping until array is empty
while l2 != []:
    print(l2.pop())

11
7
2


In [23]:
l2

[]

Submitted refined Solution Below:

In [ ]:
import numpy as np
class Solution:
    def twoSum(self, array, target):
        
        '''Inputs are an array of integer numbers and an integer  target. Outputs the indices of two
        numbers such that they add up to the target

        NOTE: For input array with exactly one solution and element only used once.
        '''
        indices_array = []
        n = len(array) #Length of array

        if n > 2:
            # Multiple index possible solution
            for i, num in enumerate(array):
                l1 = array.copy()
                l1[i] = target+5 #make interger outside of target at selected index 
                result = np.where(np.array(l1)+num == target)[0]
                if result:
                    return [i, int(result)]

                else:
                    continue
        elif n == 2:
            # One possible solution
            return [0,1] 

        else:
            return None  

Really short and understandable solution

In [214]:
class Solution:
    def twoSum(self, array, target):
        for i in range(len(array)): #iterates from 0-length of array-1
            for j in range(len(array)): #iterates from 0-lenght of array-1
                if (array[i] + array[j] == target) and (i !=j):
                    return[i, j]